server:
  port: 8078
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 商品搜索服务接口文档
    package: com.hmall.search.controller
  db:
    database: hm-item


