server:
  port: 8083
#  tomcat:
#    threads:
#      max: 50 # 允许的最大线程数
#    accept-count: 50 # 最大排队等待数量
#    max-connections: 100 # 允许的最大连接
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true # 开启OKHttp连接池支持

hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart
spring:
  rabbitmq:
    host: 192.168.230.130 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    publisher-confirm-type: simple # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
    connection-timeout: 1s
